/* Phenome — shared nav + footer injection */
(function () {
  /* === MENU DATA — generated by build/build_menu.py, do not edit === */
  var PH_MENU = [
    {
      "key": "store",
      "trigger": "Store",
      "eyebrow": "STORE MENU",
      "href": "/store/",
      "featured": [
        {
          "name": "Comprehensive Genomic Test",
          "price": "£650",
          "href": "/store/comprehensive-genomic/",
          "img": "/assets/menu/comprehensive-genomic.webp",
          "w": 300,
          "h": 200
        },
        {
          "name": "Gut Microbiome Test",
          "price": "£200",
          "href": "/store/gut-microbiome/",
          "img": "/assets/menu/gut-microbiome.webp",
          "w": 300,
          "h": 200
        },
        {
          "name": "PhenomeTech Ring",
          "price": "from £179",
          "href": "/store/phenometech-ring/",
          "img": "/assets/menu/ring.webp",
          "w": 300,
          "h": 200
        },
        {
          "name": "Ceramic Ring",
          "price": "from £199",
          "href": "/store/phenometech-ring/",
          "img": "/assets/menu/ring-ceramic.webp",
          "w": 300,
          "h": 200
        },
        {
          "name": "Quercetin Capsules",
          "price": "£26.99",
          "href": "/supplements/quercetin-capsules/",
          "img": "/assets/menu/quercetin.svg",
          "w": 300,
          "h": 200
        }
      ],
      "columns": [
        {
          "title": "Explore store",
          "links": [
            {
              "label": "Shop all",
              "href": "/store/"
            },
            {
              "label": "Genetic tests",
              "href": "/store/genetic/"
            },
            {
              "label": "Microbiome tests",
              "href": "/store/microbiome/"
            },
            {
              "label": "Supplements",
              "href": "/store/supplements/"
            },
            {
              "label": "PhenomeTech Ring",
              "href": "/store/phenometech-ring/"
            },
            {
              "label": "Ceramic Ring",
              "href": "/store/phenometech-ring/"
            },
            {
              "label": "Shop by goal",
              "href": "/store/shop-by-goal/",
              "todo": true,
              "small": true
            },
            {
              "label": "Not sure where to start",
              "href": "/quiz/",
              "small": true
            }
          ]
        },
        {
          "title": "Quick links",
          "links": [
            {
              "label": "Track order",
              "href": "/account/orders/"
            },
            {
              "label": "Activate a kit",
              "href": "/account/activate/"
            },
            {
              "label": "Free sizing kit",
              "href": "/store/free-sizing-kit/",
              "todo": true
            },
            {
              "label": "Shipping and returns",
              "href": "/devices/ring/warranty-returns/"
            },
            {
              "label": "Contact us",
              "href": "/contact/"
            }
          ]
        },
        {
          "title": "Shop by goal",
          "links": [
            {
              "label": "Sleep and recovery",
              "href": "/store/shop-by-goal/sleep-and-recovery/",
              "todo": true
            },
            {
              "label": "Energy and focus",
              "href": "/store/shop-by-goal/energy-and-focus/",
              "todo": true
            },
            {
              "label": "Immune and everyday balance",
              "href": "/store/shop-by-goal/immune-and-everyday-balance/",
              "todo": true
            },
            {
              "label": "Movement and performance",
              "href": "/store/shop-by-goal/movement-and-performance/",
              "todo": true
            }
          ]
        }
      ]
    },
    {
      "key": "testing",
      "trigger": "Testing",
      "eyebrow": "TESTING MENU",
      "href": "",
      "featured": [],
      "columns": [
        {
          "title": "Genetic testing",
          "links": [
            {
              "label": "Comprehensive Genomic Test",
              "href": "/testing/comprehensive-genomic/"
            },
            {
              "label": "Carrier Screening Test",
              "href": "/testing/carrier-screening/"
            },
            {
              "label": "Newborn Screening Test",
              "href": "/testing/newborn-screening/",
              "note": "Sold out"
            },
            {
              "label": "Sports Performance Test",
              "href": "/testing/sports-performance/"
            },
            {
              "label": "Explore genetic testing ›",
              "href": "/testing/genetic/"
            }
          ]
        },
        {
          "title": "Microbiome testing",
          "links": [
            {
              "label": "Gut Microbiome Test",
              "href": "/testing/gut-microbiome/"
            },
            {
              "label": "Oral Microbiome Test",
              "href": "/testing/oral-microbiome/"
            },
            {
              "label": "Explore microbiome testing ›",
              "href": "/testing/microbiome/"
            },
            {
              "rule": true
            },
            {
              "label": "Compare tests",
              "href": "/testing/compare/"
            },
            {
              "label": "How testing works",
              "href": "/testing/how-it-works/"
            },
            {
              "label": "Activate a kit",
              "href": "/account/activate/"
            }
          ]
        },
        {
          "title": "More from testing",
          "links": [
            {
              "label": "What you will learn",
              "href": "/testing/what-you-will-learn/",
              "todo": true
            },
            {
              "label": "Whole genome sequencing",
              "href": "/science/whole-genome-sequencing/"
            },
            {
              "label": "Built on Illumina",
              "href": "/testing/built-on-illumina/",
              "todo": true
            },
            {
              "label": "Results & counselling",
              "href": "/app/results-and-reports/"
            },
            {
              "label": "Testing FAQs",
              "href": "/testing/faqs/",
              "todo": true
            }
          ]
        }
      ]
    },
    {
      "key": "supplements",
      "trigger": "Supplements",
      "eyebrow": "SUPPLEMENTS MENU",
      "href": "/store/supplements/",
      "featured": [],
      "columns": [
        {
          "title": "Energy & Cognition",
          "links": [
            {
              "label": "NAD+",
              "href": "/supplements/nad/",
              "note": "Liposomal"
            },
            {
              "label": "NAD+ Boost",
              "plain": true
            },
            {
              "label": "Gly-NAC",
              "plain": true
            },
            {
              "label": "Mitochondria Boost",
              "plain": true
            },
            {
              "label": "Carnitine Performance+",
              "plain": true
            },
            {
              "label": "Explore energy & cognition ›",
              "plain": true
            }
          ]
        },
        {
          "title": "Immunity & Respiratory",
          "links": [
            {
              "label": "Vitamin C",
              "plain": true,
              "note": "Liposomal"
            },
            {
              "label": "Sambucus Gummies",
              "plain": true
            },
            {
              "label": "Throat Lozenges",
              "plain": true
            },
            {
              "label": "Quercetin",
              "href": "/supplements/quercetin-capsules/",
              "todo": true
            },
            {
              "label": "Propolis",
              "href": "/supplements/propolis-throat-lozenges/",
              "todo": true
            },
            {
              "label": "Explore immunity ›",
              "plain": true
            }
          ]
        },
        {
          "title": "Anti-Inflammatory",
          "links": [
            {
              "label": "Curcumin",
              "plain": true,
              "note": "Liposomal"
            },
            {
              "label": "Joint Boost",
              "plain": true
            },
            {
              "label": "FlexiCream",
              "plain": true
            },
            {
              "label": "Bromelain",
              "href": "/supplements/bromelain-capsules/",
              "todo": true
            },
            {
              "label": "Explore anti-inflammatory ›",
              "plain": true
            }
          ],
          "below": {
            "title": "Skin & Beauty",
            "links": [
              {
                "label": "Vollagen",
                "plain": true,
                "note": "Liposomal"
              },
              {
                "label": "Multi-Collagen Powder",
                "plain": true
              },
              {
                "label": "Explore skin & beauty ›",
                "plain": true
              }
            ]
          }
        },
        {
          "title": "Everyday Essentials",
          "links": [
            {
              "label": "Iron",
              "plain": true,
              "note": "Liposomal"
            },
            {
              "label": "Magnesium",
              "plain": true,
              "note": "Liposomal"
            },
            {
              "label": "D3 + K2",
              "plain": true,
              "note": "Liposomal"
            },
            {
              "label": "Explore essentials ›",
              "plain": true
            }
          ],
          "below": {
            "title": "More from supplements",
            "links": [
              {
                "label": "Bundles",
                "plain": true
              },
              {
                "label": "Subscribe & save",
                "plain": true
              },
              {
                "label": "Why liposomal",
                "href": "/supplements/why-these-formulas/",
                "todo": true
              },
              {
                "label": "Supplement FAQs",
                "href": "/supplements/faqs/",
                "todo": true
              }
            ]
          }
        }
      ]
    },
    {
      "key": "devices",
      "trigger": "Devices",
      "eyebrow": "DEVICES MENU",
      "href": "/store/devices/",
      "featured": [],
      "columns": [
        {
          "title": "Explore devices",
          "links": [
            {
              "label": "Explore PhenomeTech Ring",
              "href": "/devices/ring/"
            },
            {
              "label": "Titanium, from £179",
              "href": "/devices/ring/compare-materials/"
            },
            {
              "label": "Ceramic, from £199",
              "href": "/devices/ring/compare-materials/"
            },
            {
              "label": "Finishes",
              "href": "/devices/ring/design/"
            },
            {
              "label": "Find your size",
              "href": "/devices/ring/find-your-size/"
            },
            {
              "label": "Compare materials",
              "href": "/devices/ring/compare-materials/",
              "small": true
            },
            {
              "label": "Ring FAQs",
              "href": "/devices/ring/faqs/",
              "todo": true,
              "small": true
            }
          ]
        },
        {
          "title": "Shop devices",
          "links": [
            {
              "label": "Shop the Ring",
              "href": "/store/phenometech-ring/"
            },
            {
              "label": "Free sizing kit",
              "href": "/store/free-sizing-kit/",
              "todo": true
            }
          ]
        },
        {
          "title": "More from devices",
          "links": [
            {
              "label": "Sleep and recovery",
              "href": "/devices/ring/what-it-measures/"
            },
            {
              "label": "Design",
              "href": "/devices/ring/design/"
            },
            {
              "label": "How it works",
              "href": "/devices/ring/how-it-works/"
            },
            {
              "label": "Battery and charging",
              "href": "/devices/ring/battery-charging/"
            },
            {
              "label": "Warranty and returns",
              "href": "/devices/ring/warranty-returns/"
            }
          ]
        }
      ]
    },
    {
      "key": "app",
      "trigger": "App",
      "eyebrow": "APP MENU",
      "href": "/app/",
      "featured": [],
      "columns": [
        {
          "title": "Explore app",
          "links": [
            {
              "label": "Explore the app",
              "href": "/app/"
            },
            {
              "label": "Your dashboard",
              "href": "/app/dashboard/"
            },
            {
              "label": "Results and reports",
              "href": "/app/results-and-reports/"
            },
            {
              "label": "Trends over time",
              "href": "/app/trends/"
            },
            {
              "label": "Book a session",
              "href": "/app/book-a-session/"
            },
            {
              "label": "Download for iOS",
              "href": "/app/download/",
              "todo": true,
              "small": true
            },
            {
              "label": "Download for Android",
              "href": "/app/download/",
              "todo": true,
              "small": true
            }
          ]
        },
        {
          "title": "Get started",
          "links": [
            {
              "label": "Create an account",
              "href": "/account/"
            },
            {
              "label": "Activate a kit",
              "href": "/account/activate/"
            },
            {
              "label": "Pair your Ring",
              "href": "/app/pair-your-ring/",
              "todo": true
            },
            {
              "label": "Import past results",
              "href": "/app/import-past-results/",
              "todo": true
            }
          ]
        },
        {
          "title": "More from app",
          "links": [
            {
              "label": "Connected data",
              "href": "/app/connected-data/",
              "todo": true
            },
            {
              "label": "Specialist sessions",
              "href": "/app/book-a-session/"
            },
            {
              "label": "Privacy and your data",
              "href": "/legal/privacy.html"
            },
            {
              "label": "App support",
              "href": "/contact/"
            }
          ]
        }
      ]
    },
    {
      "key": "science",
      "trigger": "Science",
      "eyebrow": "SCIENCE MENU",
      "href": "/science/",
      "featured": [],
      "columns": [
        {
          "title": "Explore science",
          "links": [
            {
              "label": "Our research",
              "href": "/science/our-research/"
            },
            {
              "label": "Whole genome sequencing",
              "href": "/science/whole-genome-sequencing/"
            },
            {
              "label": "Multiomics",
              "href": "/science/multiomics/"
            },
            {
              "label": "Systems biology",
              "href": "/science/systems-biology/"
            },
            {
              "label": "The Longevity Hub",
              "href": "/hub/"
            },
            {
              "label": "The experts",
              "href": "/science/the-experts/",
              "todo": true
            },
            {
              "label": "Meet the team",
              "href": "/about/",
              "small": true
            },
            {
              "label": "Partner with us",
              "href": "/careers/",
              "small": true
            }
          ]
        },
        {
          "title": "Partnerships",
          "links": [
            {
              "label": "Illumina",
              "href": "/science/partners/illumina/",
              "todo": true
            },
            {
              "label": "Academic collaborations",
              "href": "/science/partners/academic/",
              "todo": true
            },
            {
              "label": "Clinical partners",
              "href": "/science/partners/clinical/",
              "todo": true
            }
          ]
        },
        {
          "title": "Published work",
          "links": [
            {
              "label": "Standards and accreditation",
              "href": "/science/standards-and-accreditation/",
              "todo": true
            }
          ]
        }
      ]
    },
    {
      "key": "clinic",
      "trigger": "Clinic",
      "eyebrow": "CLINIC MENU",
      "href": "",
      "featured": [],
      "columns": [
        {
          "title": "Explore clinic",
          "links": [
            {
              "label": "Phenome Longevity Center",
              "plain": true
            },
            {
              "label": "Programmes",
              "plain": true
            },
            {
              "label": "Consultations",
              "plain": true
            },
            {
              "label": "The clinical team",
              "plain": true
            }
          ]
        },
        {
          "title": "Book",
          "links": [
            {
              "label": "Book a consultation",
              "plain": true
            },
            {
              "label": "Free pre consultation",
              "plain": true
            },
            {
              "label": "Locations",
              "plain": true
            }
          ]
        }
      ]
    },
    {
      "key": "support",
      "trigger": "Support",
      "eyebrow": "SUPPORT MENU",
      "href": "/contact/",
      "featured": [],
      "columns": [
        {
          "title": "Explore support",
          "links": [
            {
              "label": "Testing",
              "href": "/testing/"
            },
            {
              "label": "Supplements",
              "href": "/store/supplements/"
            },
            {
              "label": "PhenomeTech Ring",
              "href": "/devices/ring/"
            },
            {
              "label": "The app",
              "href": "/app/"
            },
            {
              "label": "Orders and delivery",
              "href": "/account/orders/"
            },
            {
              "label": "Your account",
              "href": "/account/"
            }
          ]
        },
        {
          "title": "Get help",
          "links": [
            {
              "label": "Track order",
              "href": "/account/orders/"
            },
            {
              "label": "Activate a kit",
              "href": "/account/activate/"
            },
            {
              "label": "Returns and refunds",
              "href": "/devices/ring/warranty-returns/"
            },
            {
              "label": "Report a problem",
              "href": "/contact/"
            },
            {
              "label": "Contact us",
              "href": "/contact/"
            }
          ]
        },
        {
          "title": "Helpful topics",
          "links": [
            {
              "label": "Sample collection guide",
              "href": "/support/sample-collection-guide/",
              "todo": true
            },
            {
              "label": "Reading your report",
              "href": "/support/reading-your-report/",
              "todo": true
            },
            {
              "label": "Ring sizing",
              "href": "/devices/ring/find-your-size/"
            },
            {
              "label": "Privacy and your data",
              "href": "/legal/privacy.html"
            }
          ]
        }
      ]
    }
  ];
  /* === end MENU DATA === */

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
  }

  /* One panel: an optional row of product cards, then the link columns.
     Cards link to the product and carry no purchase control — §6b allows a test to
     be explored anywhere and bought only on its own product page. */
  function panelHTML(p) {
    var h = '<div class="ph-panel" id="phPanel-' + p.key + '" data-panel="' + p.key + '" hidden>' +
            '<div class="ph-panel-inner">' +
            '<div class="ph-panel-eyebrow">' + esc(p.eyebrow) + '</div>';

    if (p.featured && p.featured.length) {
      h += '<div class="ph-panel-cards">';
      p.featured.forEach(function (f) {
        h += '<a class="ph-card" href="' + esc(f.href) + '">' +
             '<span class="ph-card-img"><img src="' + esc(f.img) + '" alt="" loading="lazy" ' +
             'decoding="async" width="' + (f.w || 1400) + '" height="' + (f.h || 930) + '"></span>' +
             '<span class="ph-card-name">' + esc(f.name) + '</span>' +
             '<span class="ph-card-price">' + esc(f.price) + '</span></a>';
      });
      h += '</div>';
    }

    /* The grid's track count comes from the data, not from a number typed into the
       stylesheet. The panels are not all the same width: Clinic draws two columns,
       most draw three, Supplements draws four. A hard-coded `repeat(3, 1fr)` put the
       fourth column on a second row underneath the first — so the count is published
       here as a custom property and shared.css reads it. */
    h += '<div class="ph-panel-cols" style="--ph-cols:' + p.columns.length + '">';

    /* One row of a panel column. Four shapes, not one:
         rule  — a drawn divider. No label, no destination, and aria-hidden because
                 it says nothing a screen reader needs; it is a line.
         plain — a label the design draws with NO page behind it and none allowed
                 (Bugra: "olmayan hiçbir sayfayi oluşturma"). It must not be an <a>.
                 href="#" and href="" would both render something that looks like a
                 control and does nothing — the fake button the PRO-GUARD exists to
                 catch, and linkcheck skips both so neither would ever go red. A
                 <span> is honest: it reads as a label, it is not focusable, and it
                 cannot be clicked.
         small — the frame draws eight links a size down from their neighbours.
         link  — everything else. */
    function row(l) {
      if (l.rule) return '<span class="ph-panel-rule" aria-hidden="true"></span>';
      var note = l.note ? '<span class="ph-panel-note">' + esc(l.note) + '</span>' : '';
      var cls = l.small ? ' class="ph-panel-sm"' : '';
      if (l.plain) {
        return '<span' + (l.small ? ' class="ph-panel-label ph-panel-sm"'
                                  : ' class="ph-panel-label"') + '>' +
               esc(l.label) + note + '</span>';
      }
      return '<a href="' + esc(l.href) + '"' + cls +
             (l.todo ? ' data-todo-link' : '') + '>' + esc(l.label) + note + '</a>';
    }

    p.columns.forEach(function (c) {
      h += '<div class="ph-panel-col"><div class="ph-panel-col-t">' + esc(c.title) + '</div>';
      c.links.forEach(function (l) { h += row(l); });
      /* A second titled block stacked under this column rather than beside it —
         Supplements draws Skin & Beauty under Anti-Inflammatory and More from
         supplements under Everyday Essentials. It lives INSIDE the column div, so
         the grid keeps its track count and nothing wraps. */
      if (c.below) {
        h += '<div class="ph-panel-col-t ph-panel-col-t2">' + esc(c.below.title) + '</div>';
        c.below.links.forEach(function (l) { h += row(l); });
      }
      h += '</div>';
    });
    return h + '</div></div></div>';
  }

  var nav = document.querySelector('[data-ph-nav]');
  if (nav) {
    /* Each panel sits inside its own .ph-item, after its trigger. That one
       arrangement gives both behaviours from CSS alone: on desktop the panel is
       positioned out of the flex row and hangs under the bar as a card; in the
       mobile drawer it stays in flow and reads as an accordion under its heading.
       The chevron added below sits between the two — nothing anywhere selects the
       panel as an adjacent sibling, and both behaviours still come from CSS with no
       second code path, but if you ever write `.ph-trigger + .ph-panel`, this is why
       it will not match. Keep the panel INSIDE the item; that part is load-bearing. */
    /* Clinic is not in the design's top row — it is the outlined pill on the right,
       and that pill IS the trigger for the Clinic panel. So it is built the same way
       as the others (item > trigger > chevron > panel, the one arrangement) but into
       a different container. Everything downstream selects on .ph-trigger and
       [data-trigger], so hover, keyboard, Escape and the active state all keep
       working without a second code path. */
    var triggers = '', clinicHTML = '';
    PH_MENU.forEach(function (p) {
      /* The trigger is a real link: clicking Store goes to /store/, the way every
         top-level item on Apple's bar does. It was a <button> that navigated nowhere,
         so the only way to reach the section itself was to open the panel and click
         again inside it.
         TWO of them have nowhere to go, and that is a decision, not an omission:
         Testing opens its panel only (Bugra, 2026-08-14: "testing sayfasi ŞİMDİLİK
         bir yere gitmesin" — for now, so this reverts the day he says so), and Clinic
         has no page at all because none may be created. Those carry href "" and are
         built as <button>, which is what a control that opens a panel and navigates
         nowhere actually is. An <a> without href is not focusable and announces
         nothing; an <a href="#"> would jump the page. Both look identical: .ph-trigger
         already resets background/border/padding and inherits the font, and the top
         row's letter-spacing comes from `.ph-links > .ph-item > .ph-trigger` (0,3,0),
         which outranks `.ph-trigger`'s own `normal` (0,1,0) for either element. */
      var t = p.href
        ? '<a class="ph-trigger" href="' + esc(p.href) + '" data-trigger="' + p.key + '" ' +
          'aria-expanded="false" aria-controls="phPanel-' + p.key + '">' +
          esc(p.trigger) + '</a>'
        : '<button class="ph-trigger" type="button" data-trigger="' + p.key + '" ' +
          'aria-expanded="false" aria-controls="phPanel-' + p.key + '">' +
          esc(p.trigger) + '</button>';
      triggers += '<div class="ph-item">' + t +
                  /* …which means the label can no longer be the thing that opens the
                     panel wherever a tap navigates. This chevron is that control. It
                     carries NO visible word — its accessible name is the trigger's own
                     label, the same signed-off string from menu.json — because copy on
                     this site comes from Figma or the brief and a script writes none.
                     CSS alone decides where it shows (see .ph-toggle in shared.css);
                     the click handler below asks the CSS rather than carrying a second
                     copy of the breakpoint. */
                  '<button class="ph-toggle" type="button" data-toggle="' + p.key + '" ' +
                  'aria-label="' + esc(p.trigger) + '" aria-expanded="false" ' +
                  'aria-controls="phPanel-' + p.key + '">' +
                  '<svg viewBox="0 0 12 12" width="12" height="12" aria-hidden="true" ' +
                  'focusable="false"><path d="M2.5 4.5 6 8l3.5-3.5" fill="none" ' +
                  'stroke="currentColor" stroke-width="1.4" stroke-linecap="round" ' +
                  'stroke-linejoin="round"/></svg></button>' +
                  panelHTML(p) + '</div>';
    });
    /* Split after the loop rather than inside it, so the markup for every panel is
       written in exactly one place. */
    (function () {
      var m = triggers.match(/<div class="ph-item">(?:(?!<div class="ph-item">)[\s\S])*?data-trigger="clinic"[\s\S]*?(?=<div class="ph-item">|$)/);
      if (m) { clinicHTML = m[0]; triggers = triggers.replace(m[0], ''); }
    })();

    nav.outerHTML =
      '<header class="ph-nav" id="phNav">' +
      '<div class="ph-nav-inner">' +
      '<a class="ph-brand" href="/index.html" aria-label="Phenome Longevity — home">' +
      '<img src="/assets/brand/phenome-logo.svg" alt="Phenome Longevity" width="770" height="118"></a>' +
      /* The design's top row is seven: Store, Testing, Supplements, Devices, App,
         Science, Support. Clinic sits on the RIGHT as an outlined pill and
         Longevity Hub is not in the row at all — it is reached from the Science
         panel, which is where the design puts it. Measured against
         docs/design-frames/phenome-navigation.png, 2026-08-13. */
      '<nav class="ph-links" id="phLinks">' + triggers + '</nav>' +
      '<div class="ph-nav-end">' +
      /* No "Find your test" here. It was ours, not the design's; Can asked twice for
         the frame's own header and overruled the argument for keeping it. The quiz
         is still linked from /testing/, /store/ and the Store panel. */
      clinicHTML +
      /* Search and cart are in the design and Can asked for them explicitly after
         being told neither function exists yet: "onları gene de ekle, onları
         developer halleder." They are NOT href="#" — each points at the real page
         that already exists, so nothing here is a dead control. The search page
         has no working search and the cart has no state; the developer wires both. */
      '<a class="ph-nav-icon" href="/hub/search/" aria-label="Search">' +
      '<svg viewBox="0 0 20 20" width="18" height="18" aria-hidden="true" fill="none" ' +
      'stroke="currentColor" stroke-width="1.6"><circle cx="9" cy="9" r="6"></circle>' +
      '<path d="M13.5 13.5 L18 18" stroke-linecap="round"></path></svg></a>' +
      '<a class="ph-nav-icon" href="/store/cart/" aria-label="Basket">' +
      '<svg viewBox="0 0 20 20" width="18" height="18" aria-hidden="true" fill="none" ' +
      'stroke="currentColor" stroke-width="1.6"><path d="M4 6h12l-1 11H5L4 6Z" ' +
      'stroke-linejoin="round"></path><path d="M7.5 6a2.5 2.5 0 0 1 5 0" ' +
      'stroke-linecap="round"></path></svg></a>' +
      '<button class="ph-burger" id="phBurger" aria-label="Menu" aria-expanded="false">' +
      '<span></span><span></span></button>' +
      '</div></div></header>';

    var header = document.getElementById('phNav');
    var open = null, openT = 0, closeT = 0;
    /* Which control opened the panel, so Escape hands focus back to it. Hover sets
       nothing, and then Escape falls back to the trigger, as it always did. */
    var openedBy = null;

    /* One panel now has two controls — the trigger, which a screen reader reaches
       first, and the chevron, which is what actually expands it wherever the label
       navigates. Their aria-expanded must never disagree, so nothing sets it alone. */
    function mark(key, state) {
      var trig = header.querySelector('[data-trigger="' + key + '"]');
      var tog = header.querySelector('[data-toggle="' + key + '"]');
      if (trig) trig.setAttribute('aria-expanded', state ? 'true' : 'false');
      if (tog) tog.setAttribute('aria-expanded', state ? 'true' : 'false');
    }

    function show(key) {
      clearTimeout(closeT);
      if (open === key) return;
      hide(true);
      var panel = header.querySelector('[data-panel="' + key + '"]');
      if (!panel) return;
      panel.hidden = false;
      mark(key, true);
      open = key;
      /* The film homepage's nav is transparent white over the footage. An open panel
         needs a ground under it, so the nav drops to its solid state while it is up
         and returns to white when it closes. */
      document.documentElement.classList.add('ph-menu-open');
    }

    function hide(immediate) {
      if (!open) { if (immediate) document.documentElement.classList.remove('ph-menu-open'); return; }
      var panel = header.querySelector('[data-panel="' + open + '"]');
      if (panel) panel.hidden = true;
      mark(open, false);
      open = null;
      openedBy = null;
      document.documentElement.classList.remove('ph-menu-open');
    }

    var hoverable = window.matchMedia('(hover: hover) and (min-width: 901px)');

    header.querySelectorAll('.ph-trigger').forEach(function (t) {
      var key = t.getAttribute('data-trigger');
      var tog = t.parentNode.querySelector('.ph-toggle');

      t.addEventListener('mouseenter', function () {
        if (!hoverable.matches) return;
        clearTimeout(openT);
        /* A short intent delay: sweeping the pointer across the bar to reach
           something else must not flash three panels on the way past. */
        openT = setTimeout(function () { show(key); }, 120);
      });
      t.addEventListener('mouseleave', function () { clearTimeout(openT); });

      /* The trigger is a link, so a click follows it — and it is only ALLOWED to,
         because something else can always open the panel: hover on a pointer device,
         the chevron wherever the CSS shows one. Where there is neither — a touch
         screen still wide enough to keep the horizontal bar, i.e. a tablet in
         landscape — the first tap opens the panel and the second follows the link,
         which is what iOS has done to hover menus since the first iPad. The question
         is put to the CSS rather than to a second copy of the 901px breakpoint, so
         the two cannot drift apart. */
      /* A trigger with nowhere to go (Testing, Clinic) is a <button>, and for it
         every one of those escape hatches is wrong: there is no link for a click to
         follow, so returning early would leave a control that visibly does nothing.
         It toggles its own panel instead, on every device. */
      var isLink = t.tagName === 'A';

      t.addEventListener('click', function (e) {
        if (!isLink) {
          e.preventDefault();
          if (open === key) hide(true); else { show(key); openedBy = t; }
          return;
        }
        if (hoverable.matches) return;
        if (tog && getComputedStyle(tog).display !== 'none') return;
        if (open === key) return;
        e.preventDefault();
        show(key);
      });

      /* The keyboard path on a hover device, where the chevron is not rendered.
         Enter follows the link now, so opening needs its own key: ArrowDown opens
         and the next Tab walks straight into the panel, which is the next thing in
         the DOM. Deliberately not an open-on-FOCUS handler — focus-to-open reopens
         the panel the instant Escape returns focus here, and traps the reader. */
      t.addEventListener('keydown', function (e) {
        if (e.key === 'ArrowDown') { e.preventDefault(); show(key); openedBy = t; }
        else if (e.key === 'ArrowUp' && open === key) { e.preventDefault(); hide(true); }
      });
    });

    header.querySelectorAll('.ph-toggle').forEach(function (g) {
      var key = g.getAttribute('data-toggle');
      g.addEventListener('click', function () {
        if (open === key) { hide(true); return; }
        show(key);
        openedBy = g;
      });
    });

    header.addEventListener('mouseleave', function () {
      if (!hoverable.matches) return;
      clearTimeout(openT);
      /* Grace on the way out: the pointer travels diagonally from the trigger to the
         panel and briefly leaves both. Closing instantly makes the menu unusable. */
      closeT = setTimeout(function () { hide(true); }, 180);
    });
    header.addEventListener('mouseenter', function () { clearTimeout(closeT); });

    document.addEventListener('keydown', function (e) {
      if (e.key !== 'Escape') return;
      if (open) {
        /* Read before hide(), which clears openedBy. Focus goes back to whichever
           control opened the panel — the chevron in the drawer, the trigger otherwise
           — so Escape never drops the reader somewhere they did not come from. */
        var back = openedBy || header.querySelector('[data-trigger="' + open + '"]');
        hide(true);
        if (back) back.focus();
        return;   /* one layer per press: the panel first, the drawer on the next one */
      }
      /* The drawer itself. Measured 2026-08-13 at 390 on 120 of 120 pages: it opened
         and Escape did nothing, because this handler returned early whenever no panel
         was open — and the drawer is the site's only full-screen overlay, which is
         precisely what the Esc rule exists for. The branch sits AFTER the panel case
         on purpose: put it before, and Escape would close the whole drawer out from
         under an open panel instead of closing the panel. */
      var drawer = document.getElementById('phLinks');
      if (drawer && drawer.classList.contains('open')) {
        drawer.classList.remove('open');
        var burgerEl = document.getElementById('phBurger');
        if (burgerEl) {
          burgerEl.setAttribute('aria-expanded', 'false');
          burgerEl.focus();
        }
      }
    });
    document.addEventListener('focusin', function (e) {
      if (open && !header.contains(e.target)) hide(true);
    });
    document.addEventListener('click', function (e) {
      if (open && !header.contains(e.target)) hide(true);
    });

    var burger = document.getElementById('phBurger');
    if (burger) burger.addEventListener('click', function () {
      var links = document.getElementById('phLinks');
      var isOpen = links.classList.toggle('open');
      burger.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
      if (!isOpen) { hide(true); burger.focus(); return; }
      /* The drawer is written BEFORE .ph-nav-end in the nav template, so it precedes
         its own burger in the DOM while sitting below it on screen: measured at 390 on
         120 of 120 pages, Tab from the burger landed on page content at y=497, outside
         the open overlay. Moving focus to the first trigger makes the drawer reachable
         in the order it is read. */
      var first = links.querySelector('.ph-trigger, a');
      if (first) first.focus();
    });

    /* Exactly one trigger may be current, matched on the panel's own section only.
       Matching on member links instead lights up every panel that happens to link
       to where you are — Support links to Testing, so a testing page marked both. */
    var path = location.pathname, best = null;
    PH_MENU.forEach(function (p) {
      if (p.href.length > 1 && path.indexOf(p.href) === 0 &&
          (!best || p.href.length > best.href.length)) best = p;
    });
    if (best) {
      var bt = header.querySelector('[data-trigger="' + best.key + '"]');
      if (bt) bt.classList.add('active');
    }
    /* Triggers are excluded on purpose. They are anchors now, so this sweep would
       otherwise mark them too — and this sweep has no longest-prefix rule, which is
       the entire reason the block above exists. One owner per decision. */
    header.querySelectorAll('.ph-links a:not(.ph-trigger)').forEach(function (a) {
      var href = a.getAttribute('href');
      if (href !== '/index.html' && path.indexOf(href) === 0) a.classList.add('active');
    });
  }

  var foot = document.querySelector('[data-ph-footer]');
  if (foot) {
    foot.outerHTML =
      '<footer class="ph-footer"><div class="wrap-wide">' +
      // line-height: the footer sets 14/18 on itself, so this 17px paragraph was
      // sitting in an 18px box — a ratio of 1.059, tighter than any heading on the
      // site and the only such pair anywhere. 25px is the tokens' loose offset for 17.
      '<p style="font-size:17px;line-height:25px;color:var(--ink);max-width:640px;margin:0 0 36px">Whole-genome and microbiome testing for a longer, healthier life. At home, clinical-grade, and built on the science.</p>' +
      '<div class="cols">' +
      '<div class="col"><div class="col-t">Testing</div>' +
      '<a href="/testing/gut-microbiome/">Gut Microbiome</a>' +
      '<a href="/testing/oral-microbiome/">Oral Microbiome</a>' +
      '<a href="/testing/comprehensive-genomic/">Comprehensive Genomic</a>' +
      '<a href="/testing/carrier-screening/">Carrier Screening</a>' +
      '<a href="/testing/newborn-screening/">Newborn Screening</a>' +
      '<a href="/testing/sports-performance/">Sports Performance</a>' +
      '<a href="/testing/microbiome/">Microbiome testing</a>' +
      '<a href="/testing/genetic/">Genetic testing</a></div>' +
      '<div class="col"><div class="col-t">Shop</div>' +
      '<a href="/devices/ring/">PhenomeTech Ring</a>' +
      '<a href="/supplements/">Supplements</a>' +
      '<a href="/store/">Shop all</a>' +
      '<a href="/quiz/">Shop by goal</a>' +
      '<a href="/store/microbiome/">Microbiome</a>' +
      '<a href="/store/genetic/">Genetic</a>' +
      '<a href="/store/devices/">Devices</a>' +
      '<a href="/store/supplements/">Supplements</a>' +
      '<a href="/store/cart/">Your bag</a>' +
      '<a href="/store/checkout/">Checkout</a></div>' +
      '<div class="col"><div class="col-t">Explore</div>' +
      '<a href="/science/">Science</a>' +
      '<a href="/science/whole-genome-sequencing/">Whole genome sequencing</a>' +
      '<a href="/science/multiomics/">Multiomics</a>' +
      '<a href="/science/systems-biology/">Systems biology</a>' +
      '<a href="/science/our-research/">Our research</a>' +
      '<a href="/app/">The App</a>' +
      '<a href="/app/#longevity-ai">Longevity AI</a>' +
      '<a href="/hub/">Longevity Hub</a>' +
      '<a href="/hub/podcast/">The Longevity Seat</a>' +
      '<a href="/hub/gut-guide/">The gut health guide</a>' +
      '<a href="/app/dashboard/">Your dashboard</a>' +
      '<a href="/app/results-and-reports/">Results and reports</a>' +
      '<a href="/app/trends/">Trends over time</a>' +
      '<a href="/app/book-a-session/">Book a session</a></div>' +
      '<div class="col"><div class="col-t">Company</div>' +
      '<a href="/about/">About</a>' +
      '<a href="/careers/">Careers</a>' +
      '<a href="/press/">Press</a>' +
      '<a href="/clinic/">The Clinic</a>' +
      '<a href="/clinic/what-to-expect/">What to expect</a>' +
      '<a href="/clinic/book/">Register your interest</a>' +
      '<a href="/contact/">Contact</a>' +
      '<a href="/testing/how-it-works/">How testing works</a>' +
      '<a href="/testing/compare/">Compare tests</a>' +
      '<a href="/devices/ring/compare-materials/">Compare ring materials</a>' +
      '<a href="/devices/ring/how-it-works/">How the Ring works</a>' +
      '<a href="/hub/search/">Search the Hub</a></div>' +
      '<div class="col"><div class="col-t">Support</div>' +
      '<a href="/contact/">Help centre</a>' +
      '<a href="/account/">Your account</a>' +
      '<a href="/account/orders/">Track an order</a>' +
      '<a href="/account/activate/">Activate a kit</a>' +
      '<a href="/legal/privacy.html">Privacy &amp; data</a>' +
      '<a href="/legal/terms.html">Terms</a><a href="/sitemap/">Sitemap</a></div>' +
      '</div>' +
      '<div class="trust" style="margin-top:40px;border-bottom:0">' +
      '<span><b>ISO 15189</b> accredited lab</span>' +
      '<span><b>GDPR</b>-compliant &amp; encrypted</span>' +
      '<span>Built on <b>Illumina</b> sequencing</span>' +
      '<span><b>Clinician-reviewed</b> reports</span></div>' +
      '<div class="rule"></div>' +
      '<p class="legal">Phenome tests are for wellness and information only and are not a substitute for professional medical advice, diagnosis or treatment. Samples are processed in accredited laboratories. Your data is encrypted and never sold.</p>' +
      '<div class="bar"><span>© 2026 Phenome Longevity Ltd. All rights reserved.</span>' +
      /* The four platform names are the deck's own — group_j's Footer frame lists
         "Instagram", "YouTube", "LinkedIn", "X" — but Phenome has supplied no accounts,
         so there is no URL to put in an href and inventing one would send a visitor to
         somebody else's page. They shipped as <a href="#"> on every one of the 127
         pages this footer is injected into: 508 controls, all showing a pointer cursor
         and all doing nothing but jumping to the top. That is 88% of the 579 href="#"
         this site serves as static HTML; the other 71 are in page content.
         Spans keep every signed-off word and stop the promise. They inherit
         .ph-footer's own colour, which is the same grey as the copyright line they sit
         opposite — no rule in shared.css targets these, so nothing there has to change.
         The day the handles arrive this goes back to four anchors and one line. */
      '<span style="display:flex;gap:20px"><span>Instagram</span><span>YouTube</span><span>LinkedIn</span><span>X</span></span></div>' +
      '</div></footer>';
  }

  /* Settle each section in as it comes into view.

     The order here is the whole point: the class that lets shared.css hide anything
     goes on only after both capability checks pass. Write the CSS to hide by default
     and add a class to reveal, and every browser that cannot run this — and every
     reader who set prefers-reduced-motion — gets a blank page. So the page ships
     visible and this makes it animate, never the other way round.

     The hero is left alone. It is the first thing on screen and fading it in makes
     the site feel slow at exactly the moment it is being judged for speed.

     The observer is one instance for the page and unobserves each section once it
     has arrived: a band settles once, and scrolling back up does not replay it. */
  function reveal() {
    if (!('IntersectionObserver' in window)) return;
    if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

    var main = document.querySelector('main');
    if (!main) return;

    var secs = [], kids = main.children, i;
    for (i = 0; i < kids.length; i++) {
      if (kids[i].tagName === 'SECTION' && !kids[i].classList.contains('hero')) secs.push(kids[i]);
    }
    if (!secs.length) return;

    document.documentElement.classList.add('ph-reveal');
    for (i = 0; i < secs.length; i++) secs[i].classList.add('ph-r');

    var io = new IntersectionObserver(function (entries) {
      for (var j = 0; j < entries.length; j++) {
        if (!entries[j].isIntersecting) continue;
        entries[j].target.classList.add('ph-in');
        io.unobserve(entries[j].target);
      }
    }, {
      /* A band starts settling a little before its top edge is reached, so it is
         upright by the time it is being read rather than arriving underneath the
         reader's eye. */
      rootMargin: '0px 0px -10% 0px',
      threshold: 0.04
    });
    for (i = 0; i < secs.length; i++) io.observe(secs[i]);
  }

  /* ---- Hero drift ----------------------------------------------------------
     A hero that is simply *there* is the last still frame on a site that now moves
     everywhere else, and it is the first thing on screen.

     The picture opens 5.5% as you scroll past it, inside .hero-img's clipped rounded
     box. Progress is measured from pageYOffset against the hero's own height, not from
     the box's position in the viewport, so at the top of the page the transform is
     exactly scale(1) — identity. That matters beyond taste: audit_layout never
     scrolls, so it always measures this element at rest.

     Verified against every probe check. A transform leaves img.width and img.height
     untouched (they are layout dimensions), so the stretched check is structurally
     blind to it. .hero-img has no textContent, so it is not a candidate in the overlap
     comparison and its text sibling is then unpaired. Nothing moves horizontally.

     Guarded here rather than in the stylesheet, because an inline transform is neither
     a transition nor an animation and the reduced-motion block cannot reach it. The
     change listener is the part reveal() does not have: a reader who turns the setting
     on mid-session should get stillness without reloading, and stopping a loop is the
     one kind of motion that can be withdrawn cleanly. */
  function drift() {
    if (!('requestAnimationFrame' in window)) return;
    if (!('IntersectionObserver' in window)) return;
    var mql = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)');
    if (!mql || mql.matches) return;

    var hero = document.querySelector('main > section.hero');
    if (!hero) return;
    var box = hero.querySelector('.hero-img, .hero-figure');
    if (!box) return;
    var img = box.querySelector('img');
    if (!img) return;

    document.documentElement.classList.add('ph-drift');

    var h = 1, live = true, queued = false, off = false;

    function measure() { h = Math.max(1, hero.offsetHeight); }
    function paint() {
      queued = false;
      if (off) return;
      var t = Math.min(1, Math.max(0, (window.pageYOffset || 0) / h));
      img.style.transform = 'scale(' + (1 + 0.055 * t).toFixed(4) + ')';
    }
    function tick() { if (live && !queued) { queued = true; requestAnimationFrame(paint); } }

    new IntersectionObserver(function (es) {
      live = es[0].isIntersecting;
      if (live) tick();
    }).observe(box);

    window.addEventListener('scroll', tick, { passive: true });
    window.addEventListener('resize', function () { measure(); tick(); }, { passive: true });
    if (mql.addEventListener) mql.addEventListener('change', function () {
      if (!mql.matches) return;
      off = true; live = false;
      img.style.transform = '';
      document.documentElement.classList.remove('ph-drift');
    });

    measure();
    paint();
  }

  /* ---- Figures that count --------------------------------------------------
     The most interesting content on the Ring pages is its numbers, and .figures is the
     one place on this site where type goes to display size outside a heading. A number
     that is simply printed is a fact; a number that arrives is a measurement.

     Seventeen rows exist across three pages and this animates EIGHT of them —
     90, 94, 62, 88, 77, 20,000, 77 on /devices/ring/ and 30 on warranty-returns.
     4.2, 6, 1:1, 2, 4, 50+, 7d, 24/7 and Free are excluded by the regex or the >= 10
     floor: they are not quantities you can count to, and counting from zero to four is
     a twitch, not a measurement.

     Three things make this safe rather than clever, and each one was paid for:

     · Only the leading TEXT NODE is ever rewritten, never innerHTML. Nine of the
       seventeen rows carry a <small> holding the unit the number belongs to, and
       innerHTML destroys the split.

     · The numeral is locked to the width of the FINAL string before a digit changes.
       Outfit has no tabular figures: "0" is 31px and "20,000" is 162px, so an unlocked
       count drags the <small> up to 130px sideways, and at 390 the 20,000-genes row
       starts unwrapped at 43px tall and finishes wrapped at 83px — 40px of real layout
       shift under everything below it. audit_layout never scrolls, so an
       observer-gated count never fires inside its CLS window at all; that is luck, not
       safety, which is why the lock is mandatory anyway.

     · The final value is written back byte for byte on EVERY exit path, including the
       catch, and the true string is on the element as its accessible name from the
       first frame. A count that is interrupted halfway leaves a wrong number on a page
       that publishes "20,000 genes", and nothing ever reads a partial one aloud. */
  function figures() {
    if (!('IntersectionObserver' in window)) return;
    if (!('requestAnimationFrame' in window)) return;
    if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

    var INT = /^\d{1,3}(,\d{3})*$/;   /* 90 · 20,000 — never 50+ · 7d · 24/7 · 4.2 · 1:1 */
    var DUR = 900;
    var nodes = document.querySelectorAll('.figure .n');
    var jobs = [], i;

    for (i = 0; i < nodes.length; i++) {
      var n = nodes[i], t = n.firstChild;
      if (!t || t.nodeType !== 3) continue;
      var orig = t.nodeValue, trimmed = orig.trim();
      if (!INT.test(trimmed)) continue;
      var target = parseInt(trimmed.replace(/,/g, ''), 10);
      if (!(target >= 10)) continue;

      var run = document.createElement('span');
      n.insertBefore(run, t);
      run.appendChild(t);
      run.style.display = 'inline-block';
      run.style.minWidth = Math.ceil(run.getBoundingClientRect().width) + 'px';

      n.setAttribute('role', 'img');
      n.setAttribute('aria-label', n.textContent.trim());

      jobs.push({ el: n, node: t, orig: orig, to: target,
                  grouped: orig.indexOf(',') !== -1 });
    }
    if (!jobs.length) return;

    function group(v) {
      var s = String(v), out = '', c = 0, k;
      for (k = s.length - 1; k >= 0; k--) {
        out = s.charAt(k) + out;
        if (++c % 3 === 0 && k > 0) out = ',' + out;
      }
      return out;
    }

    function play(job) {
      var t0 = null;
      function tick(ts) {
        try {
          if (t0 === null) t0 = ts;
          var p = (ts - t0) / DUR;
          if (p >= 1) { job.node.nodeValue = job.orig; return; }
          var v = Math.round((1 - Math.pow(1 - p, 3)) * job.to);   /* lands, not stops */
          job.node.nodeValue = job.grouped ? group(v) : String(v);
          requestAnimationFrame(tick);
        } catch (e) {
          job.node.nodeValue = job.orig;
        }
      }
      requestAnimationFrame(tick);
    }

    /* Half the figure has to be on screen before it starts, or it is over before it has
       been looked at. One-shot, like the section reveal. */
    var io = new IntersectionObserver(function (entries) {
      for (var j = 0; j < entries.length; j++) {
        if (!entries[j].isIntersecting) continue;
        io.unobserve(entries[j].target);
        for (var k = 0; k < jobs.length; k++) {
          if (jobs[k].el === entries[j].target) play(jobs[k]);
        }
      }
    }, { rootMargin: '0px 0px -15% 0px', threshold: 0.5 });

    for (i = 0; i < jobs.length; i++) io.observe(jobs[i].el);
  }

  /* ---- Stillness, mid-session ----------------------------------------------
     The reduced-motion check ran once, at load. Someone who turns the setting on while
     reading stayed on a moving site until they reloaded. Turning it on now drops the
     class that lets anything hide and marks every observed section arrived, so the page
     is painted immediately and stays painted.

     Turning it back off is deliberately not handled: content that is already on screen
     must not start animating underneath a reader. */
  function watchStill() {
    var mql = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)');
    if (!mql || !mql.addEventListener) return;
    mql.addEventListener('change', function () {
      if (!mql.matches) return;
      var de = document.documentElement;
      de.classList.remove('ph-reveal');
      de.classList.remove('ph-drift');
      var r = document.querySelectorAll('.ph-r'), i;
      for (i = 0; i < r.length; i++) r[i].classList.add('ph-in');
    });
  }

  /* ---- The product bar ----------------------------------------------------
     A product page whose only way to buy sits at the very top and the very bottom is
     asking a reader six thousand pixels of scroll to remember where the button was.
     This is the pattern every product page on the web has, and this one did not.

     It authors nothing. The name is <title> up to the site suffix; the label and the
     destination are lifted from the hero's own primary button, so the bar can never
     offer a route the page does not already offer, and can never disagree with it.
     Deliberately no price: the Ring's is written six ways across this site, and a bar
     pinned to every screen is the worst possible place to pick one.

     Gated on a hero WITH a .btn, which is what makes it a product page rather than an
     article. An IntersectionObserver on the hero rather than a scroll handler: the bar
     is on exactly when the hero is off, which is one boolean and no arithmetic.

     visibility is animated alongside opacity — a bar at opacity 0 still swallows the
     clicks of whatever is under it, and this one is pinned across the top of the page. */
  /* The buy block's media slot, when it holds more than one photograph.

     Two ways to change frame and both are the reader's: it advances on its own every
     6s, and the arrows or the dots move it by hand. Taking hold STOPS the timer for
     good — a carousel that keeps moving under someone who has just chosen a frame is
     fighting them.

     The controls ship hidden in the markup and are unhidden HERE, which is the rule
     this project keeps relearning: never render a control before the thing that makes
     it work exists, or a page without JavaScript carries buttons that do nothing.

     Motion is opacity only — no transform on the frames, so nothing moves a layout box
     and audit_layout stays quiet. A reader who asked for less motion gets no timer and
     no cross-fade, just the arrows. */
  function carousels() {
    document.querySelectorAll('[data-carousel]').forEach(function (box) {
      var frames = [].slice.call(box.querySelectorAll('img'));
      if (frames.length < 2) return;
      var prev = box.querySelector('[data-car-prev]');
      var next = box.querySelector('[data-car-next]');
      var dotBox = box.querySelector('.buy-dots');
      var dots = dotBox ? [].slice.call(dotBox.querySelectorAll('.buy-dot')) : [];
      [prev, next, dotBox].forEach(function (el) { if (el) el.hidden = false; });

      var i = 0, timer = null;
      var still = window.matchMedia('(prefers-reduced-motion: reduce)');
      /* ONE number, and it lives here. The CSS reads it back as --car-ms to size the
         fill bar, so the bar cannot promise a different moment than the timer keeps. */
      var EVERY = 6000;
      box.style.setProperty('--car-ms', EVERY + 'ms');

      function show(n) {
        i = (n + frames.length) % frames.length;
        frames.forEach(function (f, k) { f.hidden = k !== i; });
        dots.forEach(function (d, k) {
          var on = k === i;
          /* Reset the fill to empty with NO transition, then let it run. Without the
             reflow between the two writes the browser coalesces them and the bar
             never moves — it would sit full from the first frame onward. */
          var fill = d.querySelector('i');
          if (fill) {
            fill.style.transition = 'none';
            fill.style.transform = 'scaleX(0)';
            void fill.offsetWidth;
            fill.style.transition = '';
            fill.style.transform = '';
          }
          d.classList.toggle('on', on);
        });
      }
      /* Stop, and stay stopped. The class tells the CSS to fill the bar and hold it:
         a countdown that is no longer counting must not keep animating. */
      function take() {
        if (timer) { clearInterval(timer); timer = null; }
        box.classList.add('held');
      }

      if (prev) prev.addEventListener('click', function () { take(); show(i - 1); });
      if (next) next.addEventListener('click', function () { take(); show(i + 1); });
      dots.forEach(function (d, k) {
        d.addEventListener('click', function () { take(); show(k); });
      });

      /* Drive the FIRST frame through show() too. The markup marks dot 0 active, so
         without this its bar starts filling before --car-ms exists — the transition
         resolves to no duration and the bar is full on arrival, promising a change
         that is still six seconds away. */
      show(0);

      if (!still.matches) {
        timer = setInterval(function () { show(i + 1); }, EVERY);
        /* Nothing cycles off-screen: it is work nobody is watching, and it means the
           reader who scrolls back finds the frame they left rather than a random one. */
        if ('IntersectionObserver' in window) {
          new IntersectionObserver(function (es) {
            if (es[0].isIntersecting) {
              if (!timer) timer = setInterval(function () { show(i + 1); }, EVERY);
            } else if (timer) { clearInterval(timer); timer = null; }
          }, { threshold: 0 }).observe(box);
        }
      }
    });
  }

  /* The horizontal card rail's arrows.

     They do not own the scrolling — `overflow-x` does, and it already handles the
     trackpad gesture, the shift-wheel, the touch drag and the keyboard. These only
     nudge that same scroller by one card, so there is one implementation and not two.
     Apple's own rail works this way, which is why it feels right with any input.

     The buttons disable at the ends. A control that is live and does nothing is the
     fake control this project keeps removing; at an end this one is spent and says so. */
  function railx() {
    document.querySelectorAll('.railx').forEach(function (rail) {
      var track = rail.querySelector('.railx-track');
      var card = rail.querySelector('.railx-card');
      if (!track || !card) return;
      var btns = [].slice.call(rail.querySelectorAll('[data-railx]'));

      function step() {
        /* Measured from the DOM, never assumed: the card width comes from CSS that
           changes at three widths, and the gap is a token. Reading it back means the
           arrow always moves exactly one card however the layout has resolved. */
        var gap = parseFloat(getComputedStyle(track).columnGap || '0') || 0;
        return card.getBoundingClientRect().width + gap;
      }
      function sync() {
        var max = track.scrollWidth - track.clientWidth;
        btns.forEach(function (b) {
          var d = +b.getAttribute('data-railx');
          b.disabled = d < 0 ? track.scrollLeft <= 1 : track.scrollLeft >= max - 1;
        });
      }
      btns.forEach(function (b) {
        b.addEventListener('click', function () {
          track.scrollBy({ left: step() * +b.getAttribute('data-railx'), behavior: 'smooth' });
        });
      });
      track.addEventListener('scroll', sync, { passive: true });
      window.addEventListener('resize', sync);
      sync();
    });
  }

  /* The scroll-pinned moment: which point is showing.

     READS the scroll, never takes it. The section's height and `position: sticky` do
     all the work in CSS; this only turns the section's own progress into an index and
     toggles a class. No wheel listener, no preventDefault, no scrollTo — so a trackpad
     fling, PageDown, a screen reader and the scrollbar all behave exactly as they do
     everywhere else on the page. That is the difference between Apple's version of this
     and the ones that feel broken.

     A reader who asked for less motion gets every point at once and this never runs. */
  function pinned() {
    var still = window.matchMedia('(prefers-reduced-motion: reduce)');
    document.querySelectorAll('.pin').forEach(function (pin) {
      var pts = [].slice.call(pin.querySelectorAll('.pin-pt'));
      if (!pts.length) return;
      if (still.matches) { pts.forEach(function (p) { p.classList.add('on'); }); return; }

      var stage = pin.querySelector('.pin-stage');
      var cur = -1;
      function frame() {
        var r = pin.getBoundingClientRect();
        /* Progress across the stretch where the stage is STUCK — 0 the moment it
           latches, 1 the moment the section lets it go. Both ends are read off the
           stage rather than assumed: `run` is the section's height minus the stage's,
           and `top` is the sticky offset the CSS resolved. That used to be hardcoded
           as "the stage is one viewport tall and sticks at 0", which was true until
           the stage took the film's own 16:7 height and started sticking centred —
           at which point the points would have arrived early and finished before the
           band released. Ask the element, not the layout you remember. */
        var sh = stage ? stage.offsetHeight : window.innerHeight;
        var top = stage ? parseFloat(getComputedStyle(stage).top) || 0 : 0;
        var run = pin.offsetHeight - sh;
        var p = run > 0 ? Math.min(Math.max((top - r.top) / run, 0), 1) : 0;
        /* The last point holds for the final screen rather than flicking past it. */
        var i = Math.min(Math.floor(p * pts.length), pts.length - 1);
        if (i !== cur) {
          cur = i;
          pts.forEach(function (el, n) { el.classList.toggle('on', n === i); });
        }
      }
      var queued = false;
      function onScroll() {
        if (queued) return;
        queued = true;
        requestAnimationFrame(function () { queued = false; frame(); });
      }
      window.addEventListener('scroll', onScroll, { passive: true });
      window.addEventListener('resize', onScroll);
      frame();
    });
  }

  function productBar() {
    if (!('IntersectionObserver' in window)) return;

    var hero = document.querySelector('main > section.hero');
    if (!hero) return;
    var cta = hero.querySelector('a.btn');
    if (!cta || !cta.getAttribute('href')) return;

    var name = (document.title || '').split('—')[0].trim();
    if (!name) return;

    var bar = document.createElement('div');
    bar.className = 'ph-bar';
    /* Not a landmark and not a heading: it is a repeat of a control already on the
       page, so it announces itself as such and stays out of the document outline. */
    bar.setAttribute('aria-hidden', 'true');
    var inner = document.createElement('div');
    inner.className = 'ph-bar-inner';
    var n = document.createElement('span');
    n.className = 'ph-bar-name';
    n.textContent = name;
    var a = document.createElement('a');
    a.className = 'btn small';
    a.setAttribute('href', cta.getAttribute('href'));
    a.setAttribute('tabindex', '-1');
    a.textContent = cta.textContent.trim();
    inner.appendChild(n);
    inner.appendChild(a);
    bar.appendChild(inner);
    document.body.appendChild(bar);

    new IntersectionObserver(function (es) {
      var off = !es[0].isIntersecting;
      bar.classList.toggle('on', off);
      bar.setAttribute('aria-hidden', off ? 'false' : 'true');
      a.setAttribute('tabindex', off ? '0' : '-1');
    }, { threshold: 0 }).observe(hero);
  }

  /* The shop rails' arrows.
     The nav slot ships EMPTY in the markup and this fills it — the page arrives with
     a rail a finger, a trackpad or the Tab key can already move, and the arrows are
     an addition for pointer users. The other way round (ship the buttons, wire them
     later) leaves two dead controls on any page where the script does not run, which
     is the same "fake button" this page had fifteen of.
     qa_final fails the build on ONE console error, so every lookup is guarded. */
  function rails() {
    var tracks = document.querySelectorAll('[data-rail]');
    if (!tracks.length) return;
    if (!('requestAnimationFrame' in window)) return;
    var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)');

    for (var i = 0; i < tracks.length; i++) wire(tracks[i]);

    function wire(track) {
      var slot = track.parentElement &&
                 track.parentElement.querySelector('[data-rail-nav]');
      if (!slot || slot.firstChild) return;   // idempotent: never wire the same rail twice
      var raf = 0;
      var prev = mk('‹', 'Show previous products', -1);
      var next = mk('›', 'Show more products', 1);
      slot.appendChild(prev);
      slot.appendChild(next);
      sync();

      track.addEventListener('scroll', function () {
        if (raf) return;
        raf = requestAnimationFrame(function () { raf = 0; sync(); });
      }, { passive: true });
      window.addEventListener('resize', sync, { passive: true });

      function mk(glyph, label, dir) {
        var b = document.createElement('button');
        b.type = 'button';
        b.className = 'ph-rail-btn';
        b.textContent = glyph;
        b.setAttribute('aria-label', label);
        b.addEventListener('click', function () {
          var first = track.firstElementChild;
          var step = (first ? first.getBoundingClientRect().width : 300) + 16;
          track.scrollBy({
            left: dir * step * 2,
            behavior: (reduce && reduce.matches) ? 'auto' : 'smooth'
          });
        });
        return b;
      }
      function sync() {
        var max = track.scrollWidth - track.clientWidth - 1;
        prev.disabled = track.scrollLeft <= 0;
        next.disabled = track.scrollLeft >= max;
      }
    }
  }

  reveal();
  drift();
  figures();
  rails();
  watchStill();
  productBar();
  carousels();
  railx();
  pinned();
})();
