/* hub/search · the Hub search, run in the page against window.PH_SEARCH
   (hub/search/search-index.js, generated by build_index.py).

   ?q= is the query and ?f= the filter, so a result list is a link that can be
   shared and the back button walks through earlier searches. Every word of the
   query has to appear somewhere in a row; the title outweighs the description,
   which outweighs the page's headings and body. The static list in the markup is
   what a visitor without script sees. */
(function () {
  'use strict';

  var rows = window.PH_SEARCH;
  var form = document.querySelector('[data-sr-form]');
  var list = document.querySelector('[data-sr-list]');
  var head = document.querySelector('[data-sr-count]');
  var kick = document.querySelector('[data-sr-kicker]');
  var chips = [].slice.call(document.querySelectorAll('[data-sr-filter]'));
  if (!rows || !form || !list || !head) return;
  var input = form.querySelector('input[name="q"]');

  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }
  function terms(q) {
    return q.toLowerCase().split(/[^a-z0-9+À-ɏ]+/).filter(function (t) { return t.length > 0; });
  }
  function mark(text, ts) {
    var out = esc(text);
    if (!ts.length) return out;
    var re = new RegExp('(' + ts.map(function (t) { return t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }).join('|') + ')', 'gi');
    return out.replace(re, '<mark>$1</mark>');
  }

  function score(r, ts, phrase) {
    var t = r.t.toLowerCase(), d = r.d.toLowerCase(), k = (r.k || '').toLowerCase();
    var m = (r.m + ' ' + r.c.join(' ')).toLowerCase();
    var s = 0;
    for (var i = 0; i < ts.length; i++) {
      var w = ts[i], hit = 0;
      if (t.indexOf(w) > -1) hit += 10;
      if (d.indexOf(w) > -1) hit += 4;
      if (k.indexOf(w) > -1) hit += 1;
      if (m.indexOf(w) > -1) hit += 2;
      if (!hit) return 0;
      s += hit;
    }
    if (phrase && t.indexOf(phrase) > -1) s += 15;
    if (r.hub) s += 2;
    return s;
  }

  function find(q) {
    var ts = terms(q);
    if (!ts.length) return { ts: ts, res: rows.filter(function (r) { return r.hub || r.c.indexOf('Guides') > -1; }) };
    var phrase = q.trim().toLowerCase();
    var res = rows.map(function (r) { return { r: r, s: score(r, ts, phrase) }; })
      .filter(function (x) { return x.s > 0; })
      .sort(function (a, b) { return b.s - a.s; })
      .map(function (x) { return x.r; });
    return { ts: ts, res: res };
  }

  function item(r, ts) {
    var guide = r.c.indexOf('Guides') > -1 && r.hub;
    return '<li class="sr-res' + (guide ? ' is-guide' : '') + '">' +
      '<p class="sr-meta">' + esc(r.m) + '</p>' +
      '<h3 class="sr-t">' + mark(r.t, ts) + '</h3>' +
      (r.d ? '<p class="sr-d">' + mark(r.d, ts) + '</p>' : '') +
      '<a aria-label="' + esc(r.t) + '" class="link-more card-more" href="' + esc(r.u) + '"></a></li>';
  }

  function render(q, f, push) {
    var got = find(q);
    var res = got.res;

    chips.forEach(function (c) {
      var k = c.getAttribute('data-sr-filter');
      var n = k === 'all' ? res.length : res.filter(function (r) { return r.c.indexOf(k) > -1; }).length;
      c.hidden = k !== 'all' && n === 0;
      c.querySelector('i').textContent = n;
    });
    if (f !== 'all' && !res.some(function (r) { return r.c.indexOf(f) > -1; })) f = 'all';
    chips.forEach(function (c) {
      var on = c.getAttribute('data-sr-filter') === f;
      c.classList.toggle('is-on', on);
      c.setAttribute('aria-pressed', on ? 'true' : 'false');
    });
    var shown = f === 'all' ? res : res.filter(function (r) { return r.c.indexOf(f) > -1; });

    var qs = q.trim();
    if (qs) {
      head.textContent = (res.length === 1 ? '1 result' : res.length + ' results') + ' for “' + qs + '”';
      if (!res.length) head.textContent = 'No results for “' + qs + '”';
      if (kick) kick.hidden = false;
      document.title = qs + ', Search, Longevity Hub';
    } else {
      head.textContent = 'Search the Longevity Hub';
      if (kick) kick.hidden = true;
      document.title = 'Search, Longevity Hub';
    }
    list.innerHTML = shown.map(function (r) { return item(r, got.ts); }).join('');
    list.hidden = !shown.length;

    if (push !== false) {
      var u = new URL(location.href);
      if (qs) u.searchParams.set('q', qs); else u.searchParams.delete('q');
      if (f !== 'all') u.searchParams.set('f', f); else u.searchParams.delete('f');
      history[push === 'replace' ? 'replaceState' : 'pushState']({ q: qs, f: f }, '', u);
    }
    state = { q: qs, f: f };
  }

  var params = new URLSearchParams(location.search);
  var state = { q: params.get('q') || '', f: params.get('f') || 'all' };
  input.value = state.q;
  render(state.q, state.f, 'replace');

  form.addEventListener('submit', function (e) {
    e.preventDefault();
    render(input.value, state.f === 'all' ? 'all' : state.f);
    input.blur();
    var top = head.getBoundingClientRect().top + window.scrollY - 120;
    if (window.scrollY > top) window.scrollTo({ top: top });
  });
  var t;
  input.addEventListener('input', function () {
    clearTimeout(t);
    t = setTimeout(function () { render(input.value, state.f, 'replace'); }, 180);
  });
  chips.forEach(function (c) {
    c.addEventListener('click', function () { render(state.q, c.getAttribute('data-sr-filter')); });
  });
  window.addEventListener('popstate', function () {
    var p = new URLSearchParams(location.search);
    input.value = p.get('q') || '';
    render(input.value, p.get('f') || 'all', false);
  });
})();
